name: my_flutter_app_pro
description: A new Flutter project.
version: 1.4.4+27
publish_to: 'none' # Flutter packages shouldn't be published

environment:
  sdk: '^3.7.0'  # SDKのバージョン制約を追加

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # 必要なパッケージを追加
  csv: ^6.0.0  # 最新バージョンに更新
  fl_chart: ^1.0.0
  timezone: ^0.9.4

  intl: ^0.20.2
  path_provider: ^2.1.5
  package_info_plus: ^6.0.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.2
  # 🔽 追加（リストUIの展開・アイコン対応などに使用）
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.10
  provider: ^6.0.0
  awesome_notifications: ^0.10.1
  flutter_launcher_icons: ^0.14.4
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  # flutter_local_notifications: ^17.1.2
  file_picker: ^8.0.7
  share_plus: ^10.0.0
  in_app_purchase: ^3.1.13
  in_app_purchase_storekit: ^0.3.13+9   # ← iOS の管理シートAPIを含む版を明示

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/daily_insights.csv
    - assets/quotes.csv

    - assets/HappinessLevelDB1_v2.csv
    - assets/ocean_background.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon_pro_ai.png"

analyzer:
  exclude:
    - my_android_app/**
    - my_android_app/lib_bak_20250615/**
    - lib_bak_20250615/**
